# Generated by Django 5.2.3 on 2025-06-17 10:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_album_title_alter_artist_debut_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(validators=[core.models.validate_release_date]),
        ),
    ]
