# Generated by Django 5.2.3 on 2025-06-18 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients')),
                ('instructions', models.TextField(help_text='Numbered list of instructions')),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)])),
                ('cover_image', models.ImageField(default='defaults/default-recipe-cover.jpg', upload_to='recipe_covers/')),
            ],
        ),
    ]
