# Generated by Django 5.2.3 on 2025-06-25 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('year_of_birth', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('FTSY', 'Fantasy'), ('SCIFI', 'Science Fiction'), ('MYST_THRILL', 'Mystery/Thriller'), ('ROM', 'Romance'), ('HIST_FIC', 'Historical Fiction'), ('HORROR', 'Horror'), ('DYST', 'Dystopian'), ('ADVN', 'Adventure'), ('BIO_AUTOBIO', 'Biography/Autobiography'), ('SELF_HELP', 'Self Help'), ('HIST', 'History'), ('SCI', 'Science'), ('BSNS', 'Business')], default='FTSY', max_length=11)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(default='default-cover.jpg', upload_to='book_covers/')),
                ('isbn', models.CharField(max_length=15)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='review.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating must be between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.book')),
            ],
        ),
    ]
