# Generated by Django 5.2.3 on 2025-06-25 13:02

import django.utils.timezone
import review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default-cover.jpg', upload_to=review.models.book_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='review',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
