# Generated by Django 5.2.3 on 2025-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_book_cover_image_alter_review_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
